#!/usr/bin/python3
"""Fetches https://alx-intranet.hbtn.io/status."""
import urllib.request


if __name__ == "__main__":
    request = urllib.request.Request("https://alx-intranet.hbtn.io/status")
    with urllib.request.urlopen(request) as response:
        response_obj = response.read()
        print("Body response:")
        print("\t- type: {}".format(type(response_obj)))
        print("\t- content: {}".format(response_obj))
        print("\t- utf8 content: {}".format(response_obj.decode("utf-8")))
